version: "3.8"

services:

  frontend:
    image: node:18-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: npm run dev -- --host=0.0.0.0
    ports:
      - "5173:5173"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./vendor:/var/www/vendor
      # ensure your sqlite file isn't overwritten:
      - ./database:/var/www/database
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

